lane :test do
  # keychain 초기화
    create_keychain(
      name: "tempkeychian",
      password: "5781",
      timeout: 1800,
      default_keychain: true,
      unlock: true,
      lock_when_sleeps: false
    )
  # appstoreconnect apikey 정보
  app_store_connect_api_key(
      key_id: "NN2J2XJGYJ",
      issuer_id: "1fb9fd6a-b761-4284-aec8-2e5c6a46bb26",
      key_content: "-----BEGIN PRIVATE KEY-----
      MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg0r0c3b4YWjD5cSwT
      /5U868tGE6dP1nZM3oFsnmJ43F+gCgYIKoZIzj0DAQehRANCAAShv1tHE8w1Y5fu
      zNK5vIlFKmNXJ3vsljwS9LB6mktYhKTQOX8+EmW/sZrsHXeQl/sTiTNmSclSI5sQ
      VLdrEHUH
      -----END PRIVATE KEY-----"
    )
  
  # match를 실행하여 인증서 및 프로파일 불러오기
    match(
      git_url: "git@github.com:junlight94/certification_repo.git",
      storage_mode: "git",
      type: "appstore",
      readonly: true,
      keychain_name: "tempkeychian",
      keychain_password: "5781"
    )

  # cert, sign 방법의 인증
  # get_certificates
  # get_provisioning_profile

  
  # 빌드 및 내보내기 🏗
    gym(
      project: "CICDTestApp.xcodeproj",
      scheme: "CICDTestApp",
      export_options: {
        method: "app-store",
        signingStyle: "manual"
      }
    )
  # testflight 업로드
    upload_to_testflight
end