lane :test do
  # keychain 초기화
    create_keychain(
      name: ENV["KEYCHAIN_NAME"],
      password: ENV["KEYCHAIN_PASSWORD"],
      timeout: 1800,
      default_keychain: true,
      unlock: true,
      lock_when_sleeps: false
    )
  # appstoreconnect apikey 정보
  app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
    )
  
  # match를 실행하여 인증서 및 프로파일 불러오기
    match(
      readonly = true,
      clone_branch_directly = true,
      git_basic_authorization: 'junlight94@gmail.com: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',
      git_private_key: ENV["GIT_PRIVATE_KEY"],
      # git_url: "git@github.com:junlight94/certification_repo.git",
      storage_mode: "git",
      type: "appstore",
      readonly: true,
      keychain_name: ENV["KEYCHAIN_NAME"],
      keychain_password: ENV["KEYCHAIN_PASSWORD"]
    )

  # cert, sign 방법의 인증
  # get_certificates
  # get_provisioning_profile

  
  # 빌드 및 내보내기 🏗
    gym(
      project: "CICDTestApp.xcodeproj",
      scheme: "CICDTestApp",
      export_options: {
        method: "app-store",
        signingStyle: "manual"
      }
    )
  # testflight 업로드
    upload_to_testflight
end