on: # 이벤트 감지
  push: # [push, commit, pullrequest]
    branches: # 브랜치
    - main

jobs: # job 설정
  build:
    runs-on: macos-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: shimataro/ssh-key-action@v2 # shimataro/ssh-key-action@v2 ssh 인증
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo ${{ secrets.SSH_KEY }} > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa
      - uses: actions/setup-node@v2 # node 설치
        with:
          node-version: '14'
      - uses: ruby/setup-ruby@v1 # ruby 설치
        with:
          ruby-version: '3'
      - run: brew install fastlane # fastlane 설치
      - run: fastlane test --verbose # fastlane 실행
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GIT_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
